export const SET_POSTS = "POSTS/SET_POSTS";
export const FETCH_POSTS = "POSTS/FETCH_POSTS";
export const TOGGLE_IS_LOADING = "POSTS/TOGGLE_IS_LOADING";
export const FETCH_SUBREDDITS = "SUB/FETCH_SUBREDDITS";
export const CHANGE_SUBREDDIT_NAME = "SUB/CHANGE_SUBREDDIT_NAME";
export const ENABLE_SEARCH_BUTTON = "SEARCH/ENABLE_SEARCH_BUTTON";
export const DISABLE_SEARCH_BUTTON = "SEARCH/DISABLE_SEARCH_BUTTON";
export const CHANGE_SEARCHBAR_INPUT_VALUE =
  "SEARCH/CHANGE_SEARCHBAR_INPUT_VALUE";
